# Generated by Django 3.2.9 on 2021-11-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_rest_api_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmruser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
