# Generated by Django 3.2.8 on 2021-11-06 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_rest_api_server', '0002_cmruser_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_nip', models.CharField(max_length=10)),
                ('company_address', models.CharField(default=None, max_length=100)),
                ('company_city', models.CharField(default=None, max_length=50)),
                ('company_is_deleted', models.BooleanField(default=False)),
                ('company_added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_rest_api_server.cmruser')),
                ('company_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_rest_api_server.business')),
            ],
        ),
    ]
