# Generated by Django 3.2.8 on 2021-11-08 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_rest_api_server', '0004_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_contents', models.TextField(max_length=1000)),
                ('note_is_deleted', models.BooleanField(default=False)),
                ('note_added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_rest_api_server.cmruser')),
                ('note_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_rest_api_server.company')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_surname', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=9)),
                ('contact_mail', models.EmailField(max_length=254)),
                ('contact_position', models.CharField(max_length=100)),
                ('contact_is_deleted', models.BooleanField(default=False)),
                ('contact_added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_rest_api_server.cmruser')),
                ('contact_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_rest_api_server.company')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
