# Generated by Django 3.2.8 on 2021-11-13 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_rest_api_server', '0005_contactperson_tradenote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmruser',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='cmruser',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='crm_rest_api_server.roles'),
        ),
    ]
